---
# - hosts: "app_north_virginia_lex_dev"
- hosts: "{{ deploy_host_name }}"
  become: yes
  strategy: free
  vars_files:
    - "vars/main.yml"
  roles:
    - role: deploy-portainer
      tags: [deploy-portainer]
    - role: deploy-sentry
      tags: [deploy-sentry]
    - role: deploy-fusionauth]
      tags: [deploy-fusionauth]
    
    


