---
# - hosts: "app_north_virginia_lex_dev"
- hosts: "{{ deploy_host_name }}"
  become: yes
  strategy: free
  vars_files:
    - "vars/main.yml"
  roles:

    - role: provision-postgres
      tags: [provision-postgres]
    
    - role: provision-sqlite
      tags: [provision-sqlite]
    
    - role: provision-mysql
      tags: [provision-mysql]
    
    - role: provision-redis
      tags: [provision-redis]

    - role: provision-elasticsearch
      tags: [provision-elasticsearch]

    - role: provision-mongo
      tags: [provision-mongo]